on:
  workflow_dispatch:
    #  https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
    inputs:
      GITHUB_USER:
        description: "GITHUB_USER"
        required: true
        type: string
      GITHUB_TOKEN:
        description: "GITHUB_TOKEN"
        required: true
        type: string
      BITBUCKET_EMAIL:
        description: "BITBUCKET_EMAIL"
        required: true
        type: string
      BITBUCKET_TOKEN:
        description: "BITBUCKET_TOKEN (API Token)"
        required: true
        type: string
      BITBUCKET_WORKSPACE:
        description: "BITBUCKET_WORKSPACE (required)"
        required: true
        type: string
      REPO_VISIBILITY:
        description: "REPO_VISIBILITY (optional)"
        required: false
        default: "auto"
        type: choice
        options:
          - auto
          - public
          - private

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
      - run: |
          go run . -target bitbucket
        env:
          GITHUB_USER: ${{ inputs.GITHUB_USER }}
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          BITBUCKET_EMAIL: ${{ inputs.BITBUCKET_EMAIL }}
          BITBUCKET_TOKEN: ${{ inputs.BITBUCKET_TOKEN }}
          BITBUCKET_WORKSPACE: ${{ inputs.BITBUCKET_WORKSPACE }}
          REPO_VISIBILITY: ${{ inputs.REPO_VISIBILITY }}
